### PR TITLE
Add missing meta-annotations on the Command annotation interface + fix command_help

### PR DESCRIPTION
**Pull request by enimiste**
- If not done, this annotation will never be gotten using reflexion in the
EngineCommandRepository

- Help command stops if finds a method without @command annotation,

- Normally it should ignore other methods (wait, notify, ....) that aren't
annotated with @command, and show only others.

### CODE REVIEW

**Comment by enimiste** [comment]
Sorry for this way of doing this pull request,
future ones will go in their specific branch.

**Comment by Muirrum** [comment]
Hey, this fails to build on my machine. The errors are about not being able to find the symbols for the `@Command` annotation definitions.

I'm just marking it as invalid until you fix these.

**Comment by enimiste** [comment]
can you past here the complete error msg and steps that you followed to get this error. so i can reproduce the same error and fix it.
for me i opened the project with eclipse as gradle project, then i do right click on the project the Gradle the update project. 
the java that i used is 1.8.
and i runned the project and it works for me.

**Comment by Muirrum** [comment]
@enimiste here's the scan: https://scans.gradle.com/s/6dlvwrsmozqy4

**Comment by enimiste** [comment]
maybe there is a merge issue, can you check files contents before compling with scans.gradle.com? 
maybe the Command.java contains both old and new code, because it says that Command clzss already defined....

**Review by Muirrum — APPROVED** [review]
Code looks good, it compiles, and works fine.

**Comment by Muirrum** [comment]
@all-contributors please add @enimiste for code

**Comment by enimiste** [comment]
Hi @Dev-Osmium,
Can you please update labels of this pull request ?
Thanks

**Comment by Muirrum** [comment]
@enimiste thanks for reminding me!

**Pull request merged**
